// 此文件由 iconfont-sync 自动生成，请勿手动修改。
// 项目：self-web    图标数：21

export type IconType =
  | 'React'
  | 'Typescript'
  | 'Vue'
  | 'agent'
  | 'ai-agent'
  | 'bianji'
  | 'daima'
  | 'diannaoyulan'
  | 'filter-records'
  | 'fuzhi'
  | 'gongcheng'
  | 'hei'
  | 'houduankaifa'
  | 'icon-suibi'
  | 'icon-test'
  | 'javascript'
  | 'juejin'
  | 'nodejs'
  | 'qq'
  | 'webpack'
  | 'xingneng'
